# Generated by Django 5.0.6 on 2024-11-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
    ]
